#!/usr/bin/env python3
"""
Generate random range query bounds for 1024d data.

Reads: repo-root 1024d-uniq-100k.bin (100k points × 1024 dims × float32)
Outputs: tests/testdata/1024d_rq_lower.bin, tests/testdata/1024d_rq_upper.bin
         (N_QUERIES × 1024 × float32)

The bounds are generated by:
1. Picking random seed points from the dataset
2. Iteratively adjusting bounds to get target number of matches (10-100)
"""
import numpy as np
import os
import argparse

# Match C++ configuration
NUM_DIMENSIONS = 1024
SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
REPO_ROOT = os.path.abspath(os.path.join(SCRIPT_DIR, ".."))
DEFAULT_DATA_FILE = os.path.join(REPO_ROOT, "1024d-uniq-100k.bin")
DEFAULT_OUTPUT_DIR = os.path.join(REPO_ROOT, "tests", "testdata")

def count_matches(data, lower, upper):
    """Count how many points fall within the given bounds."""
    in_range = np.all((data >= lower) & (data <= upper), axis=1)
    return np.sum(in_range)

def main():
    parser = argparse.ArgumentParser(description="Generate range query bounds")
    parser.add_argument("--num-queries", type=int, default=20, help="Number of queries to generate")
    parser.add_argument("--seed", type=int, default=42, help="Random seed for reproducibility")
    parser.add_argument("--min-matches", type=int, default=10, help="Minimum matches per query")
    parser.add_argument("--max-matches", type=int, default=100, help="Maximum matches per query")
    parser.add_argument("--data-file", type=str,
                        default=DEFAULT_DATA_FILE,
                        help="Path to the data file")
    parser.add_argument("--output-lower", type=str,
                        default=os.path.join(DEFAULT_OUTPUT_DIR, "1024d_rq_lower.bin"),
                        help="Path to lower bounds output")
    parser.add_argument("--output-upper", type=str,
                        default=os.path.join(DEFAULT_OUTPUT_DIR, "1024d_rq_upper.bin"),
                        help="Path to upper bounds output")
    args = parser.parse_args()

    np.random.seed(args.seed)
    
    # Load dataset
    print(f"Loading data from {args.data_file}...")
    data = np.fromfile(args.data_file, dtype=np.float32)
    num_points = len(data) // NUM_DIMENSIONS
    data = data.reshape(num_points, NUM_DIMENSIONS)
    print(f"Loaded {num_points} points with {NUM_DIMENSIONS} dimensions")
    
    # Generate queries
    lower_bounds = np.zeros((args.num_queries, NUM_DIMENSIONS), dtype=np.float32)
    upper_bounds = np.zeros((args.num_queries, NUM_DIMENSIONS), dtype=np.float32)
    
    # Pick random seed points
    seed_indices = np.random.choice(num_points, args.num_queries, replace=False)
    
    # Compute data statistics
    data_min = data.min(axis=0)
    data_max = data.max(axis=0)
    data_range = data_max - data_min
    
    print(f"Generating {args.num_queries} queries targeting {args.min_matches}-{args.max_matches} matches...")
    
    for i, idx in enumerate(seed_indices):
        seed_point = data[idx]
        
        # Start with full range, then iteratively constrain dimensions until we hit target
        lower = data_min.copy()
        upper = data_max.copy()
        
        # Shuffle dimensions to constrain in random order
        dims_to_try = np.random.permutation(NUM_DIMENSIONS)
        
        # Target: get between min_matches and max_matches
        current_matches = count_matches(data, lower, upper)
        
        for d in dims_to_try:
            if current_matches <= args.max_matches:
                break  # We're in the target range
                
            # Try constraining this dimension with progressively tighter bounds
            for scale in [0.5, 0.3, 0.2, 0.1, 0.05, 0.02, 0.01]:
                half_width = scale * data_range[d] / 2
                test_lower = lower.copy()
                test_upper = upper.copy()
                test_lower[d] = max(data_min[d], seed_point[d] - half_width)
                test_upper[d] = min(data_max[d], seed_point[d] + half_width)
                
                new_matches = count_matches(data, test_lower, test_upper)
                
                # Accept if we're still above min_matches
                if new_matches >= args.min_matches:
                    lower = test_lower
                    upper = test_upper
                    current_matches = new_matches
                    
                    if current_matches <= args.max_matches:
                        break  # Found good constraint for this dim
        
        lower_bounds[i] = lower
        upper_bounds[i] = upper
        
        print(f"  Query {i+1}/{args.num_queries}: {current_matches} matches")
    
    # Save outputs
    os.makedirs(os.path.dirname(args.output_lower), exist_ok=True)
    os.makedirs(os.path.dirname(args.output_upper), exist_ok=True)
    lower_path = args.output_lower
    upper_path = args.output_upper
    
    lower_bounds.tofile(lower_path)
    upper_bounds.tofile(upper_path)
    
    print(f"Saved lower bounds to {lower_path} ({os.path.getsize(lower_path)} bytes)")
    print(f"Saved upper bounds to {upper_path} ({os.path.getsize(upper_path)} bytes)")
    print("Done!")

if __name__ == "__main__":
    main()
